#!/usr/bin/bash

if command -v pacman &>/dev/null; then
  echo "Detected Arch-based system."
  sudo pacman -Sy --needed --noconfirm wget

elif command -v apt &>/dev/null; then
  echo "Detected Debian/Ubuntu-based system."
  sudo apt update
  sudo apt install -y wget

elif command -v dnf &>/dev/null; then
  echo "Detected Fedora-based system."
  sudo dnf install -y wget

elif command -v zypper &>/dev/null; then
  echo "Detected openSUSE-based system."
  sudo zypper refresh
  sudo zypper install -y wget unzip

elif command -v xbps-install &>/dev/null; then
  echo "Detected Void Linux."
  sudo xbps-install -Sy wget unzip

elif command -v emerge &>/dev/null; then
  echo "Detected Gentoo."
  sudo emerge -aq wget unzip

else
  echo "Unsupported Linux distribution."
  echo "Please install wget and an unziping utility manually."
  exit 1

fi

cd ~

sleep 1

cd ~/postmarketOS-spacewar/

wget https://github.com/howtoedittv/postmarketOS-spacewar/releases/download/r/lin.tar.gz

sleep 1

tar -xvf lin.tar.gz && cd lin

wget https://mirrorbits.lineageos.org/full/Spacewar/20260107/lineage-23.0-20260107-nightly-Spacewar-signed.zip
sleep 1
wget https://github.com/topjohnwu/Magisk/releases/download/v30.6/Magisk-v30.6.apk
sleep 1
wget https://github.com/MindTheGapps/16.0.0-arm64/releases/download/MindTheGapps-16.0.0-arm64-20250812_214353/MindTheGapps-16.0.0-arm64-20250812_214353.zip
cd ~/postmarketOS-spacewar/

rm -rf lin.tar.gz
