#!/usr/bin/bash

if command -v pacman &>/dev/null; then
  echo "Detected Arch-based system."
  sudo pacman -Sy --needed --noconfirm wget unzip

elif command -v apt &>/dev/null; then
  echo "Detected Debian/Ubuntu-based system."
  sudo apt update
  sudo apt install -y wget unzip xz

elif command -v dnf &>/dev/null; then
  echo "Detected Fedora-based system."
  sudo dnf install -y wget unzip xz

elif command -v zypper &>/dev/null; then
  echo "Detected openSUSE-based system."
  sudo zypper refresh
  sudo zypper install -y wget unzip xz

elif command -v xbps-install &>/dev/null; then
  echo "Detected Void Linux."
  sudo xbps-install -Sy wget unzip xz

elif command -v emerge &>/dev/null; then
  echo "Detected Gentoo."
  sudo emerge -aq wget unzip xz

else
  echo "Unsupported Linux distribution."
  echo "Please install wget and an unziping utility and xz manually."
  exit 1

fi

cd ~/postmarketOS-spacewar/des/

sleep 1

wget https://github.com/howtoedittv/postmarketOS-spacewar/releases/download/p/Phosh.tar.gz.xz

sleep 1

xz -d Phosh.tar.gz.xz
tar -xvf Phosh.tar.gz
cd Phosh
